USE EMS;
-- Drop database EMS; Create database EMS;
USE EMS;
INSERT INTO COURSEMODULE(NAME) VALUES("MTECH");
INSERT INTO COURSEMODULE(NAME) VALUES("GIDPSA");
INSERT INTO SUBJECT(TAGNAME) VALUES("JAVA");
INSERT INTO SUBJECT(TAGNAME) VALUES("HCI");
INSERT INTO SUBJECT(TAGNAME) VALUES(".NET");
